export const EQUIPMENT_REQUEST_CREATE_REQUEST = "EQUIPMENT_REQUEST_CREATE_REQUEST";
export const EQUIPMENT_REQUEST_CREATE_SUCCESS = "EQUIPMENT_REQUEST_CREATE_SUCCESS";
export const EQUIPMENT_REQUEST_CREATE_FAIL = "EQUIPMENT_REQUEST_CREATE_FAIL";
export const EQUIPMENT_REQUEST_CREATE_RESET = "EQUIPMENT_REQUEST_CREATE_RESET";

export const EQUIPMENT_REQUEST_LIST_REQUEST = "EQUIPMENT_REQUEST_LIST_REQUEST";
export const EQUIPMENT_REQUEST_LIST_SUCCESS = "EQUIPMENT_REQUEST_LIST_SUCCESS";
export const EQUIPMENT_REQUEST_LIST_FAIL = "EQUIPMENT_REQUEST_LIST_FAIL";

export const EQUIPMENT_REQUEST_DETAILS_REQUEST = "EQUIPMENT_REQUEST_DETAILS_REQUEST";
export const EQUIPMENT_REQUEST_DETAILS_SUCCESS = "EQUIPMENT_REQUEST_DETAILS_SUCCESS";
export const EQUIPMENT_REQUEST_DETAILS_FAIL = "EQUIPMENT_REQUEST_DETAILS_FAIL";

export const EQUIPMENT_REQUEST_UPDATE_REQUEST = "EQUIPMENT_REQUEST_UPDATE_REQUEST";
export const EQUIPMENT_REQUEST_UPDATE_SUCCESS = "EQUIPMENT_REQUEST_UPDATE_SUCCESS";
export const EQUIPMENT_REQUEST_UPDATE_FAIL = "EQUIPMENT_REQUEST_UPDATE_FAIL";
export const EQUIPMENT_REQUEST_UPDATE_RESET = "EQUIPMENT_REQUEST_UPDATE_RESET";

export const EQUIPMENT_REQUEST_DELETE_REQUEST = "EQUIPMENT_REQUEST_DELETE_REQUEST";
export const EQUIPMENT_REQUEST_DELETE_SUCCESS = "EQUIPMENT_REQUEST_DELETE_SUCCESS";
export const EQUIPMENT_REQUEST_DELETE_FAIL = "EQUIPMENT_REQUEST_DELETE_FAIL";

